[package]
name = "{{project-name}}"
description = "{{description}}"
version = "0.1.0"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4" }